AWSTemplateFormatVersion: 2010-09-09
Parameter:
  ProjectName:
    Type: String
  MicroServiceName:
    Type: String
  ListenerContainerPort:
    Type: String
  CertificationArn:
    Type: String
  PrivateSubnetA:
    Type: String
  PrivateSubnetB:
    Type: String
  LoadBalancerName:
    Type: String
  SecurityGroup:
    Type: String
  CertificateArn:
    Type: String

Resources:
#############################
# LoadBalancer and Listener #
#############################
  LoadBalancerALB:
    Type: AWS::ElasticLoadBalancerV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Type: application
      Scheme: internal
      Subnets:
      - Ref: PrivateSubnetOne
      - Ref: PrivateSubnetTwo
      SecurityGroup:
        - Ref: SecurityGroup
      Tags:
      - Key: 
        Value:

  ListenerALB:
    Type: AWS::ElasticLoadBalancerV2::Listener
    Properties:
      Certificates:
      - CertificationArn: !Ref CertificateArn
      DefaultActions:
      - Type: fixed-response
        FixedResponseConfig:
          ContentType: "application/json"
          MenssageBody: "{ \"alb\": \"rota default\" }"
          StatusCode: "403"
      LoadBalancerArn: !Ref LoadBalancerALB
      Port: !Ref ListenerContainerPort
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06

###############################
# LogGroup MetricFilter Alarm #
###############################
  CloudWatchGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${ProjectName}-${MicroServiceName}"
      RetentionInDays: 7

  404MetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "${ProjectName}-${MicroServiceName}"
      FilterPattern: "[ip, identity, user_id, timestamp, request, status_code = 404, size, ...]"
      MetricTrTransformations:
      - MetricValue: '1'
        MetricNamespace: !Sub "${ProjectName}-${MicroServiceName}/404s"
        MetricName: !Sub "${ProjectName}-${MicroServiceName}/404Count"
    DependsOn: CloudWatchGroup
  
  404Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "Alarm-${ProjectName}-${MicroServiceName}-404s"
      AlarmDescription: "Alarm Description"
      MetricName: !Sub "${ProjectName}-${MicroServiceName}/404Count"
      Namespace: !Sub "${ProjectName}-${MicroServiceName}/404s"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      AlarmActions:
        - '{{resolve:ssm:/org/member/workload_local_sns_arn:1}}'
      OKActions:
        - '{{resolve:ssm:/org/member/workload_local_sns_arn:1}}'
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
    DependsOn: 404MetricFilter

###########
# Outputs #
###########
Outputs:
  ListenerALB:
    Description: ARN do Listener do ALB
    Value: !Ref ListenerALB
    Export:
      Name: !Sub "${AWS::StackName-ArnListenerAlb}"