AWSTemplateFormatVersion: 2010-09-09
Parameter:
  ProjectName:
    Type: String
  MicroServiceName:
    Type: String
  ECSServiceName:
    Type: String

Resources:
##############################################
# Criação de Cluster ECS baseado em Fargate #
##############################################
  ESCCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ECSServiceName, Cluster]]
      Tags:
      - Key: 
        Value: 

###############################
# LogGroup MetricFilter Alarm #
###############################
  CloudWatchGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${ProjectName}-${MicroServiceName}"
      RetentionInDays: 7

  404MetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "${ProjectName}-${MicroServiceName}"
      FilterPattern: "[ip, identity, user_id, timestamp, request, status_code = 404, size, ...]"
      MetricTrTransformations:
      - MetricValue: '1'
        MetricNamespace: !Sub "${ProjectName}-${MicroServiceName}/404s"
        MetricName: !Sub "${ProjectName}-${MicroServiceName}/404Count"
    DependsOn: CloudWatchGroup
  
  404Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "Alarm-${ProjectName}-${MicroServiceName}-404s"
      AlarmDescription: "Alarm Description"
      MetricName: !Sub "${ProjectName}-${MicroServiceName}/404Count"
      Namespace: !Sub "${ProjectName}-${MicroServiceName}/404s"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      AlarmActions:
        - '{{resolve:ssm:/org/member/workload_local_sns_arn:1}}'
      OKActions:
        - '{{resolve:ssm:/org/member/workload_local_sns_arn:1}}'
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
    DependsOn: 404MetricFilter